export const TOGGEL_CART_HIDDEN = 'TOGGEL_CART_HIDDEN';
export const ADD_ITEM_CART = 'ADD_ITEM_CART';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
export const CLEAR_ITEM_CART = 'CLEAR_ITEM_CART';
